Stay with Softlayer library <=5.7.2
According to https://github.com/softlayer/softlayer-python  we have to stay Softlayer library <=5.7.2 since we are using python 3.5.2
This is to avoid
AttributeError: module 'os' has no attribute 'PathLike'
Details ---> https://github.com/gitpython-developers/GitPython/issues/1219